import { SiteConfig } from 'config/definitions/sites';

export const DEFAULT: SiteConfig[] = [
  {
    name: 'local',
    host: 'http://localhost:8000',
    apiPrefix: '/ispyb/api/v1',
    sampleCSVColumns: [
      'parcel name',
      'container name',
      'container type',
      'container position',
      'protein acronym',
      'sample acronym',
      'pin barcode',
      'SPG',
      'cellA',
      'cellB',
      'cellC',
      'cellAlpha',
      'cellBeta',
      'cellGamma',
      'experimentType',
      'aimed Resolution',
      'required Resolution',
      'beam diameter',
      'number of positions',
      'aimed multiplicity',
      'aimed completeness',
      'forced SPG',
      'radiation sensitivity',
      'smiles',
      'total rot. angle',
      'min osc. angle',
      'observed resolution',
      'exposure time',
      'oscillation range',
      'energy',
      'transmission range',
      'comments',
    ],
    sampleOnlineColumns: [
      'id',
      'protein acronym',
      'sample name',
      'pin barcode',
      'crystal form',
      'experimentType',
      'aimed Resolution',
      'required Resolution',
      'beam diameter',
      'number of positions',
      'aimed multiplicity',
      'aimed completeness',
      'forced SPG',
      'radiation sensitivity',
      'smiles',
      'total rot. angle',
      'min osc. angle',
      'observed resolution',
      'comments',
      'ligands'
    ],
  },
];
