import { SiteConfig } from 'config/definitions/sites';

export const MAXIV: SiteConfig[] = [
  {
    name: 'MAXIV-java',
    description: 'For MX',
    javaName: 'MAXIV',
    host: 'https://ispyb.maxiv.lu.se',
    apiPrefix: '/ispyb/ispyb-ws/rest',
    javaMode: true,
    javaConfig: {
      techniques: {
        MX: {
          beamlines: [
            { name: 'BioMAX', sampleChangerType: 'ISARA' },
            { name: 'MicroMAX', sampleChangerType: 'ISARA' },
          ],
        },
      },
    },
    sampleCSVColumns: [
      'parcel name',
      'container name',
      'container type',
      'container position',
      'protein acronym',
      'sample acronym',
      'SPG',
      'cellA',
      'cellB',
      'cellC',
      'cellAlpha',
      'cellBeta',
      'cellGamma',
      'experimentType',
      'aimed Resolution',
      'beam diameter',
      'aimed completeness',
      'total rot. angle',
      'min osc. angle',
      'exposure time',
      'oscillation range',
      'energy',
      'transmission range',
      'comments',      
    ],
    sampleOnlineColumns: [
      'id',
      'protein acronym',
      'sample name',
      'crystal form',
      'experimentType',
      'aimed Resolution',
      'beam diameter',
      'aimed completeness',
      'total rot. angle',
      'min osc. angle',
      'exposure time',
      'oscillation range',
      'energy',
      'transmission range',
      'comments',
      'ligands'
    ],
  },
];
