import { SiteConfig } from 'config/definitions/sites';

export const NETLIFY: SiteConfig[] = [
  {
    name: 'ESRF-java',
    description: 'For MX/EM',
    javaName: 'ESRF',
    host: 'https://ispyb.esrf.fr',
    apiPrefix: '/ispyb/ispyb-ws/rest',
    javaMode: true,
    javaConfig: {
      techniques: {
        SAXS: { beamlines: [{ name: 'BM29' }] },
        EM: { beamlines: [{ name: 'CM01' }] },
        MX: {
          beamlines: [
            { name: 'ID23-1', sampleChangerType: 'FlexHCDDual' },
            { name: 'ID23-2', sampleChangerType: 'FlexHCDUnipuckPlate' },
            { name: 'ID29', sampleChangerType: 'FlexHCDDual' },
            { name: 'ID30A-1', sampleChangerType: 'FlexHCDUnipuckPlate' },
            { name: 'ID30A-2', sampleChangerType: 'FlexHCDDual' },
            { name: 'ID30A-3', sampleChangerType: 'FlexHCDDual' },
            { name: 'ID30B', sampleChangerType: 'FlexHCDDual' },
            { name: 'BM30A', sampleChangerType: 'FlexHCDDual' },
          ],
        },
      },
    },
    sampleCSVColumns: [
      'parcel name',
      'container name',
      'container type',
      'container position',
      'protein acronym',
      'sample acronym',
      'pin barcode',
      'SPG',
      'cellA',
      'cellB',
      'cellC',
      'cellAlpha',
      'cellBeta',
      'cellGamma',
      'experimentType',
      'aimed Resolution',
      'required Resolution',
      'beam diameter',
      'number of positions',
      'aimed multiplicity',
      'aimed completeness',
      'forced SPG',
      'radiation sensitivity',
      'smiles',
      'total rot. angle',
      'min osc. angle',
      'observed resolution',
      'comments',
    ],
    sampleOnlineColumns: [
      'id',
      'protein acronym',
      'sample name',
      'pin barcode',
      'crystal form',
      'experimentType',
      'aimed Resolution',
      'required Resolution',
      'beam diameter',
      'number of positions',
      'aimed multiplicity',
      'aimed completeness',
      'forced SPG',
      'radiation sensitivity',
      'smiles',
      'total rot. angle',
      'min osc. angle',
      'observed resolution',
      'comments',
      'ligands'
    ],
  },
  {
    name: 'ALBA',
    description: 'For MX@ALBA',
    javaName: 'ALBA',
    host: 'https://ispyb.cells.es',
    apiPrefix: '/ispyb/ispyb-ws/rest',
    javaMode: true,
    javaConfig: {
      techniques: {
        MX: {
          beamlines: [
            {
              name: 'BL13 - XALOC',
              sampleChangerType: 'FlexHCDDual',
            },
          ],
        },
      },
    },
    sampleCSVColumns: [
      'parcel name',
      'container name',
      'container type',
      'container position',
      'protein acronym',
      'sample acronym',
      'pin barcode',
      'SPG',
      'cellA',
      'cellB',
      'cellC',
      'cellAlpha',
      'cellBeta',
      'cellGamma',
      'experimentType',
      'aimed Resolution',
      'required Resolution',
      'beam diameter',
      'number of positions',
      'aimed multiplicity',
      'aimed completeness',
      'forced SPG',
      'radiation sensitivity',
      'smiles',
      'total rot. angle',
      'min osc. angle',
      'observed resolution',
      'comments',
    ],
    sampleOnlineColumns: [
      'id',
      'protein acronym',
      'sample name',
      'pin barcode',
      'crystal form',
      'experimentType',
      'aimed Resolution',
      'required Resolution',
      'beam diameter',
      'number of positions',
      'aimed multiplicity',
      'aimed completeness',
      'forced SPG',
      'radiation sensitivity',
      'smiles',
      'total rot. angle',
      'min osc. angle',
      'observed resolution',
      'comments',
      'ligands'
    ],
  },
  {
    name: 'MAXIV',
    description: 'For MX@MAXIV',
    javaName: 'MAXIV',
    host: 'https://ispyb.maxiv.lu.se',
    apiPrefix: '/ispyb/ispyb-ws/rest',
    javaMode: true,
    javaConfig: {
      techniques: {
        MX: {
          beamlines: [
            {
              name: 'BioMAX',
              sampleChangerType: 'ISARA',
            },
            {
              name: 'MicroMAX',
              sampleChangerType: 'ISARA',
            },
          ],
        },
      },
    },
    sampleCSVColumns: [
      'parcel name',
      'container name',
      'container type',
      'container position',
      'protein acronym',
      'sample acronym',
      'SPG',
      'cellA',
      'cellB',
      'cellC',
      'cellAlpha',
      'cellBeta',
      'cellGamma',
      'experimentType',
      'aimed Resolution',
      'beam diameter',
      'aimed completeness',
      'total rot. angle',
      'min osc. angle',
      'exposure time',
      'oscillation range',
      'energy',
      'transmission range',
      'comments',      
    ],
    sampleOnlineColumns: [
      'id',
      'protein acronym',
      'sample name',
      'crystal form',
      'experimentType',
      'aimed Resolution',
      'beam diameter',
      'aimed completeness',
      'total rot. angle',
      'min osc. angle',
      'exposure time',
      'oscillation range',
      'energy',
      'transmission range',
      'comments',
      'ligands'
    ],
  },
];
